import '../assets/android-chrome-192x192.png'
import '../assets/android-chrome-512x512.png'
import '../assets/apple-touch-icon.png'
import '../assets/favicon-16x16.png'
import '../assets/favicon-32x32.png'
import '../assets/favicon.ico'
import '../assets/site.webmanifest'
import '../assets/index.html'
